[build]
  base = "/opt/build/repo"
  commandOrigin = "config"
  environment = ["OPENAI_API_KEY"]
  publish = "/opt/build/repo/build"
  publishOrigin = "config"
  functionsDirectory = "/opt/build/repo/netlify/functions"
